version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: latest
    commands:
      - echo Installing Entity Framework Core tools reference - .NET CLI
      - dotnet tool install --global dotnet-ef

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore Lvmendes.Adm.ApiAdm/Lvmendes.Adm.ApiAdm.csproj
  build:
    commands:
      - echo Build started on `date`      
      - dotnet build Lvmendes.Adm.ApiAdm/Lvmendes.Adm.ApiAdm.csproj
    Outputs:
     
  post_build:
    commands:
      - echo Publish started on `date`
      - export BUCKET=recreioquentinha
      - dotnet publish -c release -o ./build_output Lvmendes.Adm.ApiAdm/Lvmendes.Adm.ApiAdm.csproj
      - aws cloudformation package \
        --template-file template.yml \
        --s3-bucket recreioquentinha \
        --output-template-file outputtemplate.yml \
        --debug
      

artifacts:
  files:
        - template.yml
        - outputtemplate.yml
 

