version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore Lvmendes.Adm.ApiAdm/Lvmendes.Adm.ApiAdm.csproj
  build:
    commands:
      - echo Build started on `date`
      - export BUCKET=recreioquentinha #or use a different bucket other than your codepipeline bucket
      - aws cloudformation package --debug --template-file template.yml --s3-bucket recreioquentinha --output-template-file outputtemplate.yml

artifacts:
    files:
     - template.yml
     - outputtemplate.yml   